"""
annotation: prompt for generation
date:
"""

forgery_attributes = {
    "Inconsistent Lighting and Shadows",
    "Irregular Image Edges",
    "Anomalous Image Texture",
    "Low Image Quality",
    "Semantic Irrationality"
}

qs = f"""
Task: Here is a fake image and it is AI-generated. You are an image forensic expert tasked with describing forgery attributes of fake images. The image is known to be AI-generated, which can include photos, artworks, digital images, etc. Therefore, do not judge the authenticity based on the type of image. Your focus should be on identifying specific forgery attributes.

Instructions:

1. Forgery Attributes: A knowledge base has been provided with common forgery attributes: {forgery_attributes}. There are five main types, but not every fake image will exhibit all of them. Find existing forgery attributes of the image, and describe these forgery attributes.

2. Response Criteria:
- If you find forgery attributes, describe them and output: {{
    "Answer": "The image is fake.",
    "Forgery Attributes": {{
        "<type of forgery attribute>": "<describe forgery attribute>",
    }}
}}
- If no forgery attributes are present, simply output: {{"Answer": "The image is real."}}
- If you are unable to determine if the image is real or fake, output: {{"Answer": "Can not determine if the image is real or fake."}}

Output Format: Only output in the following JSON format:

- Example 1: {{
    "Answer": "The image is fake.",
    "Forgery Attributes": {{
        "<type of forgery attribute>": "<describe forgery attribute>",
    }}
}}
- Example 2: {{"Answer": "The image is real."}}
- Example 3: {{"Answer": "Can not determine if the image is real or fake."}}
"""


authentic_attributes = {
    "Consistent Lighting and Shadows",
    "Smooth and Natural Image Edges",
    "Natural and Consistent Image Texture",
    "High Image Quality",
    "Semantic Rationality"
}

qs_real = f"""
Task: Here is a real image, which is captured or created from the real world, as opposed to being artificially generated by an AI system. You are an image forensic expert tasked with: describing the image content, analyzing the image attributes and deciding why this image is real instead of manipulated or AI-generated. 

Instructions: A knowledge base has been provided with common image attributes: {authentic_attributes}. There are five main types. Find according attributes proving the image authenticity and describe these attributes.

Output Format: Only output in the following JSON format. 
- If you find image attributes proving the image authenticity, describe them and output:
{{
    "Answer": "The image is real.",
    "Attributes": {{
        "<type of image attribute>": "<describe image attribute>",
    }}
}}
- If you are unable to determine if the image is real or fake, output: {{"Answer": "Can not determine if the image is real or fake."}}
- Do not output extra contents except for above json formats.
"""

